### ISSUE TITLE
Black screen for N64 games

### ISSUE THREAD

**Issue by Raulval82** [digitalLumberjack/recalbox-os#144]
Hi!

With new update 3.2.8 N64 has black screen, game is working, I have sound and it responds but no image.

**Comment by digitalLumberjack** [comment]
Yes i'm aware of that, i'll try to make it work again... That why it's a beta support :)

**Comment by Raulval82** [comment]
If I can help with any test...

**Comment by RomainOdeval** [comment]
With update 3.2.8, i tested Mario Kart 64 and it works.
But i tested Majora's Mask and it didn't work.

Difference is Majora's Mask needed "Nintendo 64 Expansion Pak" (like Donkey Kong 64, Perfect Dark, etc ...). Maybe N64 emulator used by RecalBox is not set to emule this pak ?

Raulval82, which games did you try ?

**Comment by Raulval82** [comment]
Mario 64, Mario kart, FZERO and Starwing...

**Comment by RomainOdeval** [comment]
hum ... strange ...

**Comment by digitalLumberjack** [comment]
I changed the branche where i pull mupen64 rpi version to ricrpi one's. Some things are broken in my scripts.

**Comment by Raulval82** [comment]
If is for improving we can wait... Dont worry and keep working like this! Thank you!

**Comment by Raulval82** [comment]
Solved in 3.2.9 beta 2 with a fresh installation.

**Comment by niekverw** [comment]
Hi, I also have this issue, i noticed it on 3.2.8 and thought to wait for the update, but it is still happening with 3.2.9, not sure what to do.

**Comment by Raulval82** [comment]
I solved with a fresh installation.

**Comment by fjen** [comment]
I still get a black screen with all n64 roms on 3.2.10. rpi2, fresh install, hdmi video.

**Comment by RomainOdeval** [comment]
same as fjen

**Comment by boopr** [comment]
Same here, I can't play N64 games! :(

**Comment by bobsoppe** [comment]
With a fresh installation of 3.2.11 on the rpi2, HDMI all my n64 roms are getting a black screen.
So it seems this is still broken, hope you can get this fixed, really love those n64 games. Good luck!

**Comment by jamhall** [comment]
I also have this problem using version  v3.2.11  :(

**Comment by rockaddicted** [comment]
Hello you can try this https://github.com/digitalLumberjack/recalbox-os/wiki/N64-%3A-sound-ok-but-black-screen-%28EN%29 or try the version 3.3.0 bêta.
